CREATE TABLE w_brand(
    id SERIAL,
    name VARCHAR NOT NULL,
    slug VARCHAR NOT NULL,
    source VARCHAR NOT NULL,
    img VARCHAR
);

CREATE TABLE w_product(
    id SERIAL,
    partner_product_id int4 NOT NULL,
    slug VARCHAR NOT NULL,
    name VARCHAR,
    description VARCHAR,
    manufacturer_id int4 NOT NULL,
    manufacturer VARCHAR NOT NULL,
    listing_code VARCHAR,
    model VARCHAR,
    reference_number VARCHAR,
    movement VARCHAR,
    case_material VARCHAR,
    bracelet_material VARCHAR,
    year_of_production VARCHAR,
    condition VARCHAR,
    scope_of_delivery VARCHAR,
    gender VARCHAR,
    location VARCHAR,
    price VARCHAR,
    availability VARCHAR,
    caliber_movement VARCHAR,
    power_reserve VARCHAR,
    number_of_jewels VARCHAR,
    case_diameter VARCHAR,
    water_resistance VARCHAR,
    bezel_material VARCHAR,
    crystal VARCHAR,
    dial VARCHAR,
    bracelet_color VARCHAR,
    clasp VARCHAR,
    clasp_material VARCHAR,
    base_caliber VARCHAR,
    dial_numerals VARCHAR,
    most_recent_servicing VARCHAR,
    dealer_product_code VARCHAR,
    thickness VARCHAR,
    lug_width VARCHAR,
    frequency VARCHAR,
    bracelet_length VARCHAR,
    bracelet_thickness VARCHAR,
    buckle_width VARCHAR,
    w_date timestamp,
    other VARCHAR,
    detail TEXT,
    error_log TEXT
);