CREATE TABLE w_brand(
    id SERIAL,
    name VARCHAR NOT NULL,
    slug VARCHAR NOT NULL,
    source VARCHAR NOT NULL,
    img VARCHAR
);

CREATE TABLE w_product(
    id SERIAL,
    slug VARCHAR NOT NULL,
    name VARCHAR,
    manufacturer_id int4 NOT NULL,
    manufacturer VARCHAR NOT NULL,
    listing_code VARCHAR,
    model VARCHAR,
    reference_number VARCHAR,
    movement VARCHAR,
    case_material VARCHAR,
    bracelet_material VARCHAR,
    year_of_production VARCHAR,
    condition VARCHAR,
    scope_of_delivery VARCHAR,
    gender VARCHAR,
    location VARCHAR,
    listing_code VARCHAR,
    price VARCHAR,
    availability VARCHAR,
    movement VARCHAR,
    caliber_movement VARCHAR,
    power_reserve VARCHAR,
    number_of_jewels VARCHAR,
    case_diameter VARCHAR,
    water_resistance VARCHAR,
    bezel_material VARCHAR,
    crystal VARCHAR,
    dial VARCHAR,
    bracelet_material VARCHAR,
    bracelet_color VARCHAR,
    clasp VARCHAR,
    clasp_material VARCHAR,
    date VARCHAR,
    other VARCHAR
);